on:
 #pull_request_review:
  push:
    branches:
      - "*"
    paths:
      - ".github/workflows/**"
      - "Dockerfile"
      - "assets/**"
      - "nginx/**"
   #types:
   #  - submitted

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
   #if: github.events.review.state == 'approved'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Prepare Docker image tag
        id: prepare_tag
        env:
          REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          TAG=$(echo ${GITHUB_REF#refs/heads/*} | sed -r 's#/+#-#g')
          if [ -n "${TAG}" ]; then
            if [ "${TAG}" == "master" ]; then
              TAG=latest
            fi
          else
            TAG=edge
          fi
          DOCKER_IMAGE=${REGISTRY_HOST}/${IMAGE_NAME}:${TAG}
          echo ::set-output name=date_created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build container image and push to Docker registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.prepare_tag.outputs.docker_image }}
          labels: |
            org.opencontainers.image.created=${{ steps.prepare_tag.outputs.date_created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}
